config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :galleries

  get 'home' => 'static_pages#home', :as => 'home'
  get 'contacts' => 'static_pages#contacts', :as => 'contacts'
  get 'about' => 'static_pages#about', :as => 'about'
  get 'order' => 'static_pages#order', :as => '_order'
  get 'userslist' => 'static_pages#userslist', :as => 'userslist'
  get 'privatpolicy' => 'static_pages#privatpolicy', :as => 'privatpolicy'
  get 'sitetopic' => 'static_pages#sitetopic', :as => 'sitetopic'
  get 'catalog' => 'static_pages#catalog', :as => 'catalog'
  get 'adminpanel' => 'static_pages#adminpanel', :as => 'adminpanel'
  get "sitemap.xml" => "static_pages#sitemap", format: :xml, as: :sitemap
  get "robots.txt" => "static_pages#robots", format: :text, as: :robots
  get 'facebook' => 'static_pages#facebook', :as => 'facebook'
  get 'vkontakte' => 'static_pages#vkontakte', :as => 'vkontakte'

  devise_for :users, :controllers => { registrations: 'registrations',
                                       omniauth_callbacks: 'omniauth_callbacks', sessions: 'sessions' }
  resources :users

  match 'remote_sign_up', to: 'remote_content#remote_sign_up', via: [:get]
  match 'remote_sign_in', to: 'remote_content#remote_sign_in', via: [:get]

  match '/users/:id/finish_signup' => 'users#finish_signup',
        via: [:get, :patch], as: :finish_signup

  resources :categories do
    member do
      get :session_update
      get :catalog
      post :temp_update
      patch :temp_update
    end
  end

  devise_scope :user do
    get "sign_out", to: "devise/sessions#destroy"
  end

  root 'static_pages#home'

end

app/controllers/static_pages_controller.rb
#   class StaticPagesController
#   Copyright (c) 2015-2016, Sergy Nazarevich.
#   This file is licensed under the Common Domain General Public License..

class StaticPagesController < ApplicationController
  before_action :require_admin, only: [:userslist, :adminpanel, :modpanel]
  def home

  end

  def contacts

  end

  def about

  end

  def catalog

  end

  def order

  end

  def userslist
    @users = User.all
  end

  def privatpolicy

  end

  def adminpanel

  end

  def modpanel

  end

  def sitemap
    path = Rails.root.join("public", "sitemaps", "sitemap.xml")
    if File.exists?(path)
      render xml: open(path).read
    else
      render text: "Sitemap not found.", status: :not_found
    end
  end

  def robots
    render :partial => "static_pages/robots.text.haml"
  end

  def sitetopic
    @categories = Category.where("categories.visible = 't'").order('categories.id ASC')
  end

  def facebook
    render :partial => 'facebook'
  end

  def vkontakte
    render :partial => 'vkontakte'
  end
end

app/views/static_pages/_robots.text.haml
User-agent: *
Disallow: #{new_user_session_path}
Disallow: #{new_user_registration_path}
Disallow: #{remote_sign_in_path}
Disallow: #{remote_sign_up_path}
Disallow: /remote_sign_up
Disallow: /remote_sign_in

app/views/static_pages/about.html.haml
#s-about-us.section.page-about.page.page-cent.fp-section.fp-table{:style => "height: 609px;"}
  .fp-tableCell.fp-content{:style => "height: 609px;"}
    %section.content
      %header.p-title
        %h3
          Про нас
          %i.ion.ion-android-information
        %h1 Мы делаем мебель
      %article.text
        %p Мебель на заказ любой сложности и ценовой категории. Мебель для кухни, шкаф-купе, детская мебель, гостинная, прихожая, офисная мебель для руководителей и персонала.
        %p
          Преимущества работы с нами:
        %ul{:type => "square"}
          %li
            %i.icon.ion.ion-checkmark.green>
            индивидуальный подход к каждому проекту
          %li
            %i.icon.ion.ion-checkmark.green>
            высокое качество изготовления мебели
          %li
            %i.icon.ion.ion-checkmark.green>
            не надо будет бегать по магазинам в поисках мебели нужных вам размеров
          %li
            %i.icon.ion.ion-checkmark.green>
            вы получите именно то, что вам необходимо, с нужным количеством полочек, ящичков, и т. д.
          %li
            %i.icon.ion.ion-checkmark.green>
            оптимальная цена на мебель исходя из Ваших возможностей и предпочтений
          %li
            %i.icon.ion.ion-checkmark.green>
            широкий выбор материалов и фурнитуры на любой самый изысканый вкус
        %p
          В работе используется массив дуба,ясеня,ольхи. Отделка производится лакокрасочной продукцией ведущих европейских производителей : "Sirka", "AkzoNOBEL", "Remers" и т.п. В изделиях используется фурнитура фирм "Вlum", "Hettich", "Hafele", "Gamet"."
    %footer.p-footer.p-scrolldown
      %a{:href => "#con"}
        .arrow-d
          .before Контакт
          .after Сообщение
          .circle

app/views/static_pages/adminpanel.html.haml
#adminpanel
  = render 'admin_menu'
  = render 'admin_panel_controlls'
:javascript
  $('.navbar-nav li').removeClass('active');
  $('.navbar-nav li.btn-nav-adminpanel').addClass('active');

app/views/static_pages/catalog.html.haml
#s-catalog.section.page-when.page.page-cent.fp-section.fp-table{"data-anchor" => "cat", :style => "height: 609px;"}
  .fp-tableCell.fp-content{:style => "height: 609px;"}
    %section.content
    %footer.p-footer.p-scrolldown
      %a{:href => "#reg"}
        .arrow-d
          .before Быть на
          .after связи
          .circle

app/views/static_pages/contacts.html.haml
#s-contact.section.page-contact.page.page-cent.bg-color.fp-section{"data-anchor" => "con", "data-bgcolor" => "rgba(95, 25, 208, 0.88)s", :style => "height: 609px;"}
  / Begin of contact information
  .fp-slides
    .fp-slidesContainer{:style => "width: 200%;"}
      #information.slide.fp-slide.fp-table.active{"data-anchor" => "con/info", :style => "width: 50%;"}
        .fp-tableCell.fp-content{:style => "height: 609px;"}
          %section.content
            %header.p-title
              %h3
                Contact
                %i.ion.ion-location
              %ul.buttons
                %li.show-for-medium-up
                  %a{:href => "#about-us", :title => "About"}
                    %i.ion.ion-android-information
                /
                /  <li>
                /  <a title="Contact" href="#contact/information"><i class="ion ion-location"></i></a>
                /  </li>
                %li
                  %a{:href => "#mssg", :title => "Message"}
                    %i.ion.ion-email
            / Begin Of Page SubSction
            .contact
              .row
                .medium-6.columns.left
                  %ul
                    %li
                      %h4 Email
                      %p
                        %a{:href => "mailto://sergkoval@gmail.com"} sergkoval@gmail.com"
                      %p
                        %a{:href => "mailto://mikita67@gmail.com"} mikita67@gmail.com"
                    %li
                      %h4 Address
                      %p
                        Хмельницкий
                        = succeed "\u{443}\u{43b}.\u{417}\u{430}\u{440}\u{435}\u{447}\u{430}\u{43d}\u{441}\u{43a}\u{430}\u{44f}" do
                          %br/
                    %li
                      %h4 Phone
                      %p
                        %strong Отдел технологии и дизайна:
                        %br/
                        +380 673947080
                        +380 980669464
                      %p
                        %strong Дирекция:
                        %br/
                        +380 673823377
                        +380 677008835
                .medium-6.columns.social-links.right
                  %ul
                    / legal notice
                    %li.show-for-medium-up
                      %h4 Website
                      %p
                        %a{:href => "http://www.vinner-plus.com"} www.vinner-plus.com
                    %li.show-for-medium-up
                      %h4 Найди нас на
                      / Begin of Social links
                      .socialnet
                        %a{:href => "#"}
                          %i.ion.ion-social-facebook
                        %a{:href => "#"}
                          %i.ion.ion-social-instagram
                        %a{:href => "#"}
                          %i.ion.ion-social-twitter
                        %a{:href => "#"}
                          %i.ion.ion-social-pinterest
                        %a{:href => "#"}
                          %i.ion.ion-social-tumblr
                    / End of Social links
                    %li
                      %p
                        %img.logo{:alt => "Logo", :src => "img/logo_large.png"}/
                      %p.small
                        %strong
                          %a{:href => "http://vinner-plus.com"} VinnerPlus©2017
                        All right reserved
      / End of page SubSection
      #s-message.slide.fp-slide.fp-table{"data-anchor" => "con/mssg", :style => "width: 50%;"}
        .fp-tableCell.fp-content{:style => "height: 609px;"}
          %section.content
            %header.p-title
              %h3
                Write to us
                %i.ion.ion-email
              %ul.buttons
                %li.show-for-medium-up
                  %a{:href => "#ab", :title => "About"}
                    %i.ion.ion-android-information
                %li
                  %a{:href => "#information", :title => "Contact"}
                    %i.ion.ion-location
            /
            /      <li>
            /      <a title="Message" href="#contact/message"><i class="ion ion-email"></i></a>
            /      </li>
            / Begin Of Page SubSction
            .page-block.c-right.v-zoomIn
              .wrapper
                %div
                  %form.message.form.send_message_form{:action => "ajaxserver/serverfile.php", :method => "get"}
                    .fields.clearfix
                      .input
                        %label{:for => "mes-name"} Name
                        %input#mes-name{:name => "name", :placeholder => "Your Name", :required => "", :type => "text"}/
                      .buttons
                        %button#submit-message.button.email_b{:name => "submit_message"} Ok
                    .fields.clearfix
                      .input
                        %label{:for => "mes-email"} Email
                        %input#mes-email{:name => "email", :placeholder => "Email Address", :required => "", :type => "email"}/
                    .fields.clearfix.no-border
                      %label{:for => "mes-text"} Message
                      %textarea#mes-text{:name => "message", :placeholder => "Message ...", :required => ""}
                      %div
                        %p.message-ok.invisible Your message has been sent, thank you.
  / End Of Page SubSction
  .fp-controlArrow.fp-prev
  .fp-controlArrow.fp-next

app/views/static_pages/home.html.haml
= content_for :leftpanel do
  = render partial: 'leftpanel'
#s-home.section.page-home.page.page-cent.fp-section.active.fp-table{"data-anchor" => "tut", :style => "height: 609px;"}
  .fp-tableCell.fp-content{:style => "height: 609px;"}
    / Content
    %section.content
      %header.header
        .h-left
          %h2
            %img.h-logo-biggest{:alt => "Vinner Plus", :src => "img/logo-biggest.png"}/
        .h-right
          %h3
            Мебельная
            = succeed "\u{444}\u{430}\u{431}\u{440}\u{438}\u{43a}\u{430}" do
              %br/
          %h4.subhead
            %a{:href => "#cat"} КАТАЛОГ
    / Scroll down button
    %footer.p-footer.p-scrolldown
      %a{:href => "#cat"}
        .arrow-d
          .before Посмотреть
          .after КАТАЛОГ
          .circle
= render partial: 'catalog'
= render partial: 'feedback'
= render partial: 'about'
= render partial: 'contact'
= content_for :last_script do
  :javascript
    $(document).ready(function(callback) {
      get_fullpages('tut:cat:fback:ab:con');
    });

app/views/static_pages/modpanel.html.haml
#modpanel

app/views/static_pages/order.html.haml
.top_box.clearfix
%section#order.topwhite
:javascript
  get_order();
  show_order_tab();
  $('.main-nav li').removeClass('active');
  $('.main-nav li.btn-nav-order').addClass('active');

app/views/static_pages/privatpolicy.html.haml
#privatpolicy.col-sm-10
  %h1
    Privacy Policy

  %p
    This privacy policy has been compiled to better serve those who are concerned with how their 'Personally identifiable information' (PII) is being used online. PII, as used in US privacy law and information security, is information that can be used on its own or with other information to identify, contact, or locate a single person, or to identify an individual in context. Please read our privacy policy carefully to get a clear understanding of how we collect, use, protect or otherwise handle your Personally Identifiable Information in accordance with our website.

  %h3
    What personal information do we collect from the people that visit our blog, website or app?

  %p
    When ordering or registering on our site, as appropriate, you may be asked to enter your name, email address, phone number, credit card information or other details to help you with your experience.

  %h3
    When do we collect information?

  %p
    We collect information from you when you register on our site, place an order, Open a Support Ticket or enter information on our site.

  %h3
    How do we use your information?

  %p
    We may use the information we collect from you when you register, make a purchase, sign up for our newsletter, respond to a survey or marketing communication, surf the website, or use certain other site features in the following ways:

    %ol
      To personalize user's experience and to allow us to deliver the type of content and product offerings in which you are most interested.
    %ol
      To allow us to better service you in responding to your customer service requests.
    %ol
      To quickly process your transactions.

  %h3
    How do we protect visitor information?

  %p
    Our website is scanned on a regular basis for security holes and known vulnerabilities in order to make your visit to our site as safe as possible.

  %p
    We use regular Malware Scanning.

  %p
    Your personal information is contained behind secured networks and is only accessible by a limited number of persons who have special access rights to such systems, and are required to keep the information confidential. In addition, all sensitive/credit information you supply is encrypted via Secure Socket Layer (SSL) technology.

  %p
    We implement a variety of security measures when a user enters, submits, or accesses their information to maintain the safety of your personal information.

  %p
    All transactions are processed through a gateway provider and are not stored or processed on our servers.

  %h3
    Do we use 'cookies'?

  %p
    Yes. Cookies are small files that a site or its service provider transfers to your computer's hard drive through your Web browser (if you allow) that enables the site's or service provider's systems to recognize your browser and capture and remember certain information. For instance, we use cookies to help us remember and process the items in your shopping cart. They are also used to help us understand your preferences based on previous or current site activity, which enables us to provide you with improved services. We also use cookies to help us compile aggregate data about site traffic and site interaction so that we can offer better site experiences and tools in the future.

  %p
    We use cookies to:
    %ol
      Help remember and process the items in the shopping cart.
    %ol
      Understand and save user's preferences for future visits.

  %p
    You can choose to have your computer warn you each time a cookie is being sent, or you can choose to turn off all cookies. You do this through your browser (like Internet Explorer) settings. Each browser is a little different, so look at your browser's Help menu to learn the correct way to modify your cookies.

  %p
    If users disable cookies in their browser:

  %p
    If you disable cookies off, some features will be disabled It will turn off some of the features that make your site experience more efficient and some of our services will not function properly.

  %p
    However, you can still place orders buy items over the telephone by contacting customer service.

  %h3
    Third-party disclosure

  %p
    We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information unless we provide users with advance notice. This does not include website hosting partners and other parties who assist us in operating our website, conducting our business, or serving our users, so long as those parties agree to keep this information confidential. We may also release information when it's release is appropriate to comply with the law, enforce our site policies, or protect ours or others' rights, property, or safety.

  %p
    However, non-personally identifiable visitor information may be provided to other parties for marketing, advertising, or other uses.

  %h3
    Third-party links

  %p
    We do not include or offer third-party products or services on our website.

  %h3
    Google

  %p
    Google's advertising requirements can be summed up by Google's Advertising Principles. They are put in place to provide a positive experience for users. https://support.google.com/adwordspolicy/answer/1316548?hl=en

  %p
    We use Google AdSense Advertising on our website.

  %p
    Google, as a third-party vendor, uses cookies to serve ads on our site. Google's use of the DART cookie enables it to serve ads to our users based on previous visits to our site and other sites on the Internet. Users may opt-out of the use of the DART cookie by visiting the Google Ad and Content Network privacy policy.

  %p
    We have implemented the following:
    %ol
      Remarketing with Google AdSense

  %p
    We along with third-party vendors, such as Google use first-party cookies (such as the Google Analytics cookies) and third-party cookies (such as the DoubleClick cookie) or other third-party identifiers together to compile data regarding user interactions with ad impressions and other ad service functions as they relate to our website.

  %h3
    Opting out:
  %p
    Users can set preferences for how Google advertises to you using the Google Ad Settings page. Alternatively, you can opt out by visiting the Network Advertising initiative opt out page or permanently using the Google Analytics Opt Out Browser add on.

  %h3
    California Online Privacy Protection Act

  %p
    CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law's reach stretches well beyond California to require a person or company in the United States (and conceivably the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals with whom it is being shared, and to comply with this policy. - See more at: http://consumercal.org/california-online-privacy-protection-act-caloppa/#sthash.0FdRbT51.dpuf

  %p
    According to CalOPPA we agree to the following:
  %p
    Users can visit our site anonymously.
  %p
    Once this privacy policy is created, we will add a link to it on our home page or as a minimum on the first significant page after entering our website.
  %p
    Our Privacy Policy link includes the word 'Privacy' and can be easily be found on the page specified above.

  %p
    Users will be notified of any privacy policy changes:
    %ol
      On our Privacy Policy Page
  %p
    Users are able to change their personal information:
    %ol
      By logging in to their account

  %p
    How does our site handle do not track signals?
  %p
    We honor do not track signals and do not track, plant cookies, or use advertising when a Do Not Track (DNT) browser mechanism is in place.

  %p
    Does our site allow third-party behavioral tracking?
  %p
    It's also important to note that we do not allow third-party behavioral tracking

  %h3
    COPPA (Children Online Privacy Protection Act)

  %p
    When it comes to the collection of personal information from children under 13, the Children's Online Privacy Protection Act (COPPA) puts parents in control. The Federal Trade Commission, the nation's consumer protection agency, enforces the COPPA Rule, which spells out what operators of websites and online services must do to protect children's privacy and safety online.

  %p
    We do not specifically market to children under 13.

  %h3
    Fair Information Practices

  %p
    The Fair Information Practices Principles form the backbone of privacy law in the United States and the concepts they include have played a significant role in the development of data protection laws around the globe. Understanding the Fair Information Practice Principles and how they should be implemented is critical to comply with the various privacy laws that protect personal information.

  %p
    In order to be in line with Fair Information Practices we will take the following responsive action, should a data breach occur:
  %p
    We will notify the users via email
    %ol
      Within 7 business days
  %p
    We will notify users via phone call
    %ol
      Within 7 business days
  %p
    We will notify the users via in-site notification
    %ol
      Within 1 business day

  %p
    We also agree to the Individual Redress Principle, which requires that individuals have a right to pursue legally enforceable rights against data collectors and processors who fail to adhere to the law. This principle requires not only that individuals have enforceable rights against data users, but also that individuals have recourse to courts or government agencies to investigate and/or prosecute non-compliance by data processors.

  %h3
    CAN SPAM Act

  %p
    The CAN-SPAM Act is a law that sets the rules for commercial email, establishes requirements for commercial messages, gives recipients the right to have emails stopped from being sent to them, and spells out tough penalties for violations.

  %p
    We collect your email address in order to:
    %ol
      Process orders and to send information and updates pertaining to orders.
    %ol
      We may also send you additional information related to your product and/or service.

  %p
    To be in accordance with CANSPAM we agree to the following:
    %ol
      NOT use false or misleading subjects or email addresses.
    %ol
      Identify the message as an advertisement in some reasonable way.
    %ol
      Include the physical address of our business or site headquarters.
    %ol
      Monitor third-party email marketing services for compliance, if one is used.
    %ol
      Honor opt-out/unsubscribe requests quickly.
    %ol
      Allow users to unsubscribe by using the link at the bottom of each email.

  %p
    If at any time you would like to unsubscribe from receiving future emails, you can email us at
    %ol
      Follow the instructions at the bottom of each email and we will promptly remove you from ALL correspondence.

app/views/static_pages/sitetopic.html.haml
.top_box.clearfix
%section#sitetopic.col-sm-10
  %table.table.table-striped.table-order-history-item{:role => "grid"}
    %thead
      %caption
        = t(:_topic)
    %tbody
      %tr
        %td= link_to t(:_home), home_path
      %tr
        %td= link_to t(:_about), about_path
      %tr
        %td= link_to t(:_contact_us), contacts_path
      %tr
        %td= link_to t('registrations.new.sign_up'), remote_sign_up_path
      %tr
        %td= link_to t('layouts.header.login'), remote_sign_in_path
      %tr
        %td= link_to t(:_order), _order_path
      %tr
        %td= link_to t(:_catalog), catalog_path
      - @categories.each do |c|
        %tr
          %td
            %a{href: "/catalog?id=#{c.id}"}
              - if c.id == 2
                = t('category.two')
              - if c.id == 3
                = t('category.three')
              - if c.id == 10
                = t('category.ten')
        - Product.where("products.category_id = '#{c.id}'").each do |p|
          %tr
            %td
              %a{href: "#{view_product_path(p)}", alt: "#{p.opengraph_title}", title: "#{p.opengraph_title}"}
                = attachment_image_tag((p.picture_id && Image.find(p.picture_id)) || Image.new, :file, :fill, 90, 120, format: "jpeg", fallback: "default90x120.png", class: 'image_uploaded')
                = p.name + " - " + p.opengraph_title

app/views/static_pages/userslist.html.haml
.add-comment.add-comment-velvet.styled.col-ss450-row
  .add-comment-title
    %h3 List of Users
  .comment-form
    .form-inner
      %table.table.table-striped.table-bordered.table-condensed
        %thead
          %tr.rowSubmit
            %th
              Email
            %th
              Tickets
            %th
              Created at
        %tbody
          - @users.each do |user|
            %tr.rowSubmit
              %td
                = user.email
              %td
              %td
                = user.created_at