config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :galleries

  get 'home' => 'static_pages#home', :as => 'home'
  get 'contacts' => 'static_pages#contacts', :as => 'contacts'
  get 'about' => 'static_pages#about', :as => 'about'
  get 'order' => 'static_pages#order', :as => '_order'
  get 'userslist' => 'static_pages#userslist', :as => 'userslist'
  get 'privatpolicy' => 'static_pages#privatpolicy', :as => 'privatpolicy'
  get 'sitetopic' => 'static_pages#sitetopic', :as => 'sitetopic'
  get 'catalog' => 'static_pages#catalog', :as => 'catalog'
  get 'adminpanel' => 'static_pages#adminpanel', :as => 'adminpanel'
  get "sitemap.xml" => "static_pages#sitemap", format: :xml, as: :sitemap
  get "robots.txt" => "static_pages#robots", format: :text, as: :robots
  get 'facebook' => 'static_pages#facebook', :as => 'facebook'
  get 'vkontakte' => 'static_pages#vkontakte', :as => 'vkontakte'

  devise_for :users, :controllers => { registrations: 'registrations',
                                       omniauth_callbacks: 'omniauth_callbacks', sessions: 'sessions' }
  resources :users

  match 'remote_sign_up', to: 'remote_content#remote_sign_up', via: [:get]
  match 'remote_sign_in', to: 'remote_content#remote_sign_in', via: [:get]

  match '/users/:id/finish_signup' => 'users#finish_signup',
        via: [:get, :patch], as: :finish_signup

  resources :categories do
    member do
      get :session_update
      get :catalog
      post :temp_update
      patch :temp_update
    end
  end

  devise_scope :user do
    get "sign_out", to: "devise/sessions#destroy"
  end

  root 'static_pages#home'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string
#  is_admin               :boolean          default(FALSE)
#  is_moderator           :boolean          default(FALSE)
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  temporary              :uuid
#  cell                   :string
#


class User < ActiveRecord::Base
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/


  include Gravtastic
  gravtastic

  has_many :identities

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :trackable, :validatable, :omniauthable

  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :name, :is_admin, :is_moderator, :current_sign_in_ip
  validates :email, format: { without: TEMP_EMAIL_REGEX }, on: :update
  validates :password, length: { minimum: 0, maximum: 120 },
            on: :update, allow_blank: true

  def self.find_for_oauth(auth, signed_in_resource = nil)
    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    user = signed_in_resource ? signed_in_resource : identity.user

    # find the existant user by email
    !user && user = get_user_by_email_and_auth(auth)

    # Create the user if it's a new registration
    !user && user = create_user_by_auth(auth)

    # Associate the identity with the user if needed
    identity.user != user && identity.user = user
    identity.save!
    user
  end

  def self.get_user_by_email_and_auth(auth)
    # Get the existing user by email if the provider gives us a verified email.
    # If no verified email was provided we assign a temporary email and ask the
    # user to verify it on the next step via UsersController.finish_signup
    User.find_by_email(get_email_by_auth(auth))
  end

  def self.create_user_by_auth(auth)
    user = User.new(
        name: auth.extra.raw_info.name,
        email: get_email_by_auth(auth),
        password: Devise.friendly_token[0, 20]
    )
    user.save!
    user
  end

  def self.get_email_by_auth(auth)
    if auth.info.email
      auth.info.email
    else
      "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com"
    end
  end

  def email_verified?
    email && email !~ TEMP_EMAIL_REGEX
  end

  def is_admin?
    self.is_admin
  end

  class << self
    def serialize_from_session(key,salt)
      record = to_adapter.get(key[0].to_param)
      record if record && record.authenticatable_salt == salt
    end
  end
end

app/controllers/users_controller.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string(255)
#  is_admin               :boolean          default(FALSE)
#  is_moderator           :boolean          default(FALSE)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  temporary              :uuid
#  cell                   :string(255)
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_admin, only: [:index, :show, :delete]

  # GET /users GET /users.json
  def index
    @users = User.eager_load(:identities).order('users.created_at DESC')
  end

  # GET /users/:id.:format
  def show
    # authorize! :read, @user
  end

  # GET /users/new GET /users/new.json
  def new
    @user = User.new
  end

  # POST /users POST /users.json
  def create
    @user = User.new(params[:user])
    @user.confirmed_at = Time.now
    @user.temporary = session['temporary']
    @user.skip_confirmation!
    !@user.save && (redirect_to new_user_session_path, error: 'Creating of user is fail!')
    redirect_to @user
  end

  # GET /users/:id/edit
  def edit
    # authorize! :update, @user
    @user = User.find(params[:id])
  end

  # PATCH/PUT /users/:id.:format
  def update
    @user = User.find(params[:id])
    @param = params[:user]

    if @param[:password].empty?
      @param.delete(:password)
      @param.delete(:password_confirmation)
    end

    # authorize! :update, @user
    !@user.update_attributes(@param) && ( redirect_to edit_users_path )
    !current_user && sign_in(@user, :bypass => true)
    redirect_to @user, notice: 'Your profile was successfully updated.'
  end

  # GET/PATCH /users/:id/finish_signup
  def finish_signup
    # authorize! :update, @user
    if request.patch? && params[:user] #&& params[:user][:email]
      @temp_user = User.find(params[:user][:id])
      @verified_user = User.where(email: params[:user][:email]).last

      if @verified_user
        @user = @verified_user
        if @temp_user
          @identity = Identity.where(user_id: params[:user][:id]).last
          @identity.user_id = @verified_user.id
          @identity.save
        end
      else
        @temp_user.update(params[:user][:email]) && @temp_user
        @user = @temp_user
      end

      if @user.update(user_params)
        sign_in(@user, :bypass => true)
        redirect_to root_url, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

  # DELETE /users/:id.:format
  def destroy
    # authorize! :delete, @user
    @user.destroy
    redirect_to users_path, notice: 'User was deleted successful.'
  end

  private
  def set_user
    (params[:id].to_s != 'sign_out') && @user = User.find(params[:id])
  end

  def user_params
    accessible = [ :name, :email ] # extend with your own params
    accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
    params.require(:user).permit(accessible)
  end
end

app/views/users/_form.html.haml
= form_for(@user) do |f|
  - if @user.errors.any?
    .alert.alert-error
      %b
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  %table.table.table-striped.table-bordered.table-condensed.table-user-form{:role => "grid"}
    %tr
      %td{:scope => "row"}= f.label :name
      %td= f.text_field :name
    %tr
      %td{:scope => "row"}= f.label :email
      %td= f.text_field :email
    - if current_user.is_admin?
      %tr
        %td{:scope => "row"}= f.label "Aproved rights:"
        %td
          .left
            = f.label :is_admin
            = f.check_box :is_admin
          .right
            = f.label :is_moderator
            = f.check_box :is_moderator
    %tr
      %td{:scope => "row"}= f.label :password
      %td= f.password_field :password
    %tr
      %td{:scope => "row"}= f.label :password_confirmation
      %td= f.password_field :password_confirmation
    %tr
      %td= bootstrap_icon_link_to t(:_cansel), users_path, 'glyphicon glyphicon-time icon-white', :class => "button btn btn-warning"
      %td= f.submit :class => "button btn btn-success"

app/views/users/edit.html.haml
#adminpanel
  = render 'admin_menu'
  = show_flash
  .tab-content
    %fieldset
      %legend
        Edit user: #{@user.name}
      = render 'form'
:javascript
  $('.navbar-nav li').removeClass('active');
  $('.navbar-nav li.btn-nav-adminpanel').addClass('active');
  $('.adminbar-nav li').removeClass('active');
  $('.adminbar-nav li.btn-nav-user').addClass('active');

app/views/users/finish_signup.html.haml
#add-email-back
#add-email
  %h1
    Add Email
  = form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f|
    .form-group
      = f.hidden_field :id, :class => "span5 hidden"
      = f.label 'Please, describe Your Email:'
      .controls
        = f.text_field :email, :autofocus => true, :value => '', class: 'form-control input-lg', placeholder: 'Example: email@me.com'
        %p.help-block
          Please confirm your email address. No spam.
    .actions
      = f.submit 'Continue', :class => 'btn btn-primary'

app/views/users/index.html.haml
#adminpanel
  = render 'admin_menu'
  = show_flash
  .tab-content
    %fieldset
      %legend List of users
      = bootstrap_icon_link_to t('admins.admin_panel.new_user'), new_user_path, "glyphicon glyphicon-plus icon-white", :class => "button btn btn-success btn-new"
      %table.table.table-index.table-striped.table-bordered.table-condensed{:role => "grid"}
        %thead
          %tr
            %th{:scope => "column"}
              = t('admins.headers.name_p')
            %th{:scope => "column"} email
            %th{:scope => "column"}
              = t('admins.headers.cell')
            %th{:scope => "column"} networks
            %th{:scope => "column"} s.i.count
            %th{:scope => "column"}
              = t('admins.headers.temporary')
            %th{:scope => "column"}
        %tbody
          - @users.each do |user|
            %tr
              %td
                = user.name
                - if user.is_admin
                  %span.label.label-info
                    = t('admins.headers.is_admin')
                - if user.is_moderator
                  %span.label.label-info
                    = t('admins.headers.is_moderator')
              %td= user.email
              %td= user.cell
              %td
                - result = ''
                - user.identities.each { |ident| result += ident.provider.to_s + ' ' }
                = result
              %td= user.sign_in_count
              %td= user.temporary
              %td
                = bootstrap_icon_link_to t('layouts.header.profile'), user, "glyphicon glyphicon-user icon-white", method: :get, :class => "button btn btn-small btn-primary"
                = bootstrap_icon_link_to t(:_edit), edit_user_path(user), "glyphicon glyphicon-pencil icon-white", :class => "button btn btn-small btn-primary"
                = bootstrap_icon_link_to t(:_delete), user, "glyphicon glyphicon-trash icon-white", confirm: 'Are you sure?', method: :delete, :class => "button btn btn-small btn-danger"
:javascript
  $('.navbar-nav li').removeClass('active');
  $('.navbar-nav li.btn-nav-adminpanel').addClass('active');
  $('.adminbar-nav li').removeClass('active');
  $('.adminbar-nav li.btn-nav-user').addClass('active');

app/views/users/new.html.haml
#adminpanel
  = render 'admin_menu'
  = show_flash
  .tab-content
    %fieldset
      %legend
        New user
      = render 'form'
:javascript
  $('.navbar-nav li').removeClass('active');
  $('.navbar-nav li.btn-nav-adminpanel').addClass('active');
  $('.adminbar-nav li').removeClass('active');
  $('.adminbar-nav li.btn-nav-user').addClass('active');

app/views/users/show.html.haml
#adminpanel.parallax
  = render 'admin_menu'
  = show_flash
  .tab-content
    %fieldset
      %legend
        Profile of #{@user.name}:
      %table.table.table-striped.table-bordered.table-condensed.table-user-profile{:role => "grid"}
        %tr
          %td{:scope => "row"}
            = t('admins.headers.name_p')
          %td
            = @user.name
            - if @user.is_admin
              %span.label.label-info
                = t('admins.headers.is_admin')
            - if @user.is_moderator
              %span.label.label-info
                = t('admins.headers.is_moderator')
        %tr
          %td{:scope => "row"} email
          %td= @user.email
        %tr
          %td{:scope => "row"} Current SignIn at
          %td= @user.current_sign_in_at
        %tr
          %td{:scope => "row"} Last SignIn at
          %td= @user.last_sign_in_at
        %tr
          %td{:scope => "row"} Current SignIn IP
          %td= @user.current_sign_in_ip
        %tr
          %td{:scope => "row"} Last SignIn IP
          %td= @user.last_sign_in_ip
        %tr
          %td{:scope => "row"} SignInCount
          %td= @user.sign_in_count
        %tr
          %td{:scope => "row"}
            = image_tag @user.gravatar_url
          %td
            - if current_user && (@user.id == current_user.id || current_user.is_admin || current_user.is_moderator)
              = bootstrap_icon_link_to t(:_edit), edit_user_path(@user), "glyphicon glyphicon-pencil icon-white", :class => "button btn btn-small btn-primary"
              - if current_user.is_admin
                = bootstrap_icon_link_to t(:_delete), @user, "glyphicon glyphicon-trash icon-white", confirm: 'Are you sure?', method: :delete, :class => "button btn btn-small btn-danger"
:javascript
  $('.navbar-nav li').removeClass('active');
  $('.navbar-nav li.btn-nav-adminpanel').addClass('active');
  $('.adminbar-nav li').removeClass('active');
  $('.adminbar-nav li.btn-nav-user').addClass('active');