config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :galleries

  get 'home' => 'static_pages#home', :as => 'home'
  get 'contacts' => 'static_pages#contacts', :as => 'contacts'
  get 'about' => 'static_pages#about', :as => 'about'
  get 'order' => 'static_pages#order', :as => '_order'
  get 'userslist' => 'static_pages#userslist', :as => 'userslist'
  get 'privatpolicy' => 'static_pages#privatpolicy', :as => 'privatpolicy'
  get 'sitetopic' => 'static_pages#sitetopic', :as => 'sitetopic'
  get 'catalog' => 'static_pages#catalog', :as => 'catalog'
  get 'adminpanel' => 'static_pages#adminpanel', :as => 'adminpanel'
  get "sitemap.xml" => "static_pages#sitemap", format: :xml, as: :sitemap
  get "robots.txt" => "static_pages#robots", format: :text, as: :robots
  get 'facebook' => 'static_pages#facebook', :as => 'facebook'
  get 'vkontakte' => 'static_pages#vkontakte', :as => 'vkontakte'

  devise_for :users, :controllers => { registrations: 'registrations',
                                       omniauth_callbacks: 'omniauth_callbacks', sessions: 'sessions' }
  resources :users

  match 'remote_sign_up', to: 'remote_content#remote_sign_up', via: [:get]
  match 'remote_sign_in', to: 'remote_content#remote_sign_in', via: [:get]

  match '/users/:id/finish_signup' => 'users#finish_signup',
        via: [:get, :patch], as: :finish_signup

  resources :categories do
    member do
      get :session_update
      get :catalog
      post :temp_update
      patch :temp_update
    end
  end

  devise_scope :user do
    get "sign_out", to: "devise/sessions#destroy"
  end

  root 'static_pages#home'

end

app/controllers/application_controller.rb
#   class ApplicationController
#   Copyright (c) 2015-2016, Sergy Nazarevich.
#   This file is licensed under the Common Domain General Public License.

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include HttpAcceptLanguage::AutoLocale
  before_filter :store_request_in_thread
  #before_action :set_locale
  before_action :set_session
  protect_from_forgery with: :exception
  helper_method :logged_in?

  #def set_locale
  #  #I18n.locale = I18n.default_locale
  #  #http_accept_language.compatible_language_from(I18n.available_locales) && I18n.locale = http_accept_language.compatible_language_from(I18n.available_locales)
  #  params[:locale] && I18n.locale = params[:locale]
  #end

  def set_session
    @user = User.find(current_user.id) if current_user
    !session['temporary'] && session['temporary'] = ((defined? @user) && !@user.temporary.blank? && @user.temporary) || SecureRandom.uuid
    session['history'].blank? && (session['history'] = false)
    (!session['category'] || session['category'].blank?) && (session['category'] = 3)
    (!session['view'] || session['view'].blank?) && (session['view'] = 'showcase')
    (!session['deffered'] || session['deffered'].blank?) && (session['deffered'] = Array.new)
    if current_user
      @user.temporary = session['temporary'] if (@user.temporary.blank? || @user.temporary != session['temporary'])
      @user.update(params[:temporary])
    end
  end

  def logged_in?
    session[:token].present?
  end

  def require_admin
    (!current_user || !current_user.is_admin) && (redirect_to root_path, :error => 'You are not admin!')
  end

  #def default_url_options(options={})
  #  { :locale => I18n.locale }
  #end

  def store_request_in_thread
    Thread.current[:request] = request.host_with_port
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def flash_normal
    render 'messages'
  end

  def show_flash
    f = ""
    f += "<div class=\"alert alert-success\">#{notice}</div>" if notice
    f += "<div class=\"alert alert-error\">#{alert}</div>" if alert
    f.html_safe
  end

  def bootstrap_icon_link_to (text, url, icon, html_options = {})
    link_to url, html_options do
      "<i class=\"#{icon}\"></i> #{text}".html_safe
    end
  end

  def sort_link_to (text, query, url, html_options = {})
    if defined? descA[query]
      desc_q = true
      icon = '.glyphicon-arrow-down'
    else
      desc_q = false
      icon = '.glyphicon-arrow-up'
    end
    url = url + "/?sort='#{query}'&desc='#{desc_q}'"
    link_to url, html_options do
      "#{text} <i class='.glyphicon #{icon}></i>".html_safe
    end
  end
end

app/views/application/_about.html.haml
#s-about-us.section.page-about.page.page-cent.fp-section.fp-table{:style => "height: 609px;"}
  .fp-tableCell.fp-content{:style => "height: 609px;"}
    %section.content
      %header.p-title
        %h3
          Про нас
          %i.ion.ion-android-information
        %h1 Мы делаем мебель
      %article.text
        %p Мебель на заказ любой сложности и ценовой категории. Мебель для кухни, шкаф-купе, детская мебель, гостинная, прихожая, офисная мебель для руководителей и персонала.
        %p
          Преимущества работы с нами:
        %ul{:type => "square"}
          %li
            %i.icon.ion.ion-checkmark.green>
            индивидуальный подход к каждому проекту
          %li
            %i.icon.ion.ion-checkmark.green>
            высокое качество изготовления мебели
          %li
            %i.icon.ion.ion-checkmark.green>
            не надо будет бегать по магазинам в поисках мебели нужных вам размеров
          %li
            %i.icon.ion.ion-checkmark.green>
            вы получите именно то, что вам необходимо, с нужным количеством полочек, ящичков, и т. д.
          %li
            %i.icon.ion.ion-checkmark.green>
            оптимальная цена на мебель исходя из Ваших возможностей и предпочтений
          %li
            %i.icon.ion.ion-checkmark.green>
            широкий выбор материалов и фурнитуры на любой самый изысканый вкус
        %p
          В работе используется массив дуба,ясеня,ольхи. Отделка производится лакокрасочной продукцией ведущих европейских производителей : "Sirka", "AkzoNOBEL", "Remers" и т.п. В изделиях используется фурнитура фирм "Вlum", "Hettich", "Hafele", "Gamet"."
    %footer.p-footer.p-scrolldown
      %a{:href => "#con"}
        .arrow-d
          .before Контакт
          .after Сообщение
          .circle

app/views/application/_admin_menu.html.haml
.adminbar-quiqnav
  = render partial: 'category_select'
%ul{class: ['nav', 'adminbar-nav']}
  %li{class: ['direct', 'btn-nav-dashboard', 'active']}
    %a{href: "#{adminpanel_path}", class: 'gradient'}
      %i{class: [ 'fa', 'fa-dashboard']}
      =t('activerecord.models.dashboard')
  %li{class: ['direct', 'btn-nav-user', 'btn-nav-catalog']}
    %a{href: "#{users_path}"}
      %i{class: [ 'fa', 'fa-user']}
      =t('activerecord.models.user')
  %li{class: ['direct', 'btn-nav-category']}
    %a{href: "#{categories_path}"}
      %i{class: [ 'fa', 'fa-bars']}
      =t('activerecord.models.category')
  %li{class: ['direct', 'btn-nav-image']}
    %a{href: "#{images_path}"}
      %i{class: [ 'fa', 'fa-picture-o']}
      =t('activerecord.models.image')
  %li{class: ['direct', 'btn-nav-product_code']}
    %a{href: "#product"}
      %i{class: [ 'fa', 'fa-sticky-note']}
      =t('activerecord.models.product_code')
  %li{class: ['direct', 'btn-nav-payment_type']}
    %a{href: "#product"}
      %i{class: [ 'fa', 'fa-credit-card-alt']}
      =t('activerecord.models.payment_type')
  %li{class: ['direct', 'btn-nav-order']}
    %a{href: "#product"}
      %i{class: [ 'fa', 'fa-briefcase']}
      =t('activerecord.models.order')
:javascript
  $(".quiq-link").hide();

app/views/application/_admin_panel_controlls.html.haml
.controlls

app/views/application/_catalog.html.haml
#s-catalog.section.page-when.page.page-cent.fp-section.fp-table{"data-anchor" => "cat", :style => "height: 609px;"}
  .fp-tableCell.fp-content{:style => "height: 609px;"}
    %section.content
      .catalog-notifier
        .choose-catalog-box
          - Category.where("categories.visible = true AND categories.parent_id IS NULL").each do |c|
            .box
              %a.cat_main{href: "#{catalog_category_path(c.id)}"}
                .logo
                  %img{:alt => "Logo Brand", :src => "/img/logo_large.png"}/
                = attachment_image_tag(c, :image, :fill, 100, 100, fallback: "default100x100.png", format: "png", class: 'image_uploaded')
                %span
                  = c.name
    %footer.p-footer.p-scrolldown
      %a{:href => "#fback"}
        .arrow-d
          .before Быть на
          .after связи
          .circle

app/views/application/_category_select.html.haml
.controll-group-session
  = collection_select(:category, :category_id, Category.where("categories.parent_id IS NULL"), :id, :name, {:selected => session["category"]})
:javascript
  choose_category();

app/views/application/_contact.html.haml
#s-contact.section.page-contact.page.page-cent.bg-color.fp-section{"data-anchor" => "con", "data-bgcolor" => "rgba(95, 25, 208, 0.88)s", :style => "height: 609px;"}
  / Begin of contact information
  .fp-slides
    #information.slide.fp-slide.fp-table.active{:style => "width: 50%;"}
      .fp-tableCell.fp-content{:style => "height: 609px;"}
        %section.content
          %header.p-title
            %h3
              Наши контакты!
              %i.ion.ion-location
            %ul.buttons
              %li.show-for-medium-up
                %a{:href => "#con", :title => "Контакты"}
                  %i.ion.ion-android-information
              %li
                %a{:href => "#con/1", :title => "Написать нам"}
                  %i.ion.ion-email
              %li
                %a{:href => "#con/2", :title => "Онлайн ЧАТ"}
                  %i.ion.ion-chatboxes
            / Begin Of Page SubSction
          .contact
            .row
              .medium-6.columns.left
                %ul
                  %li
                    %h4 Email
                    %p
                      %a{:href => "mailto://sergkoval@gmail.com"} sergkoval@gmail.com"
                  %li
                    %h4 Address
                    %p
                      Хмельницкий
                      = succeed "\u{443}\u{43b}.\u{417}\u{430}\u{440}\u{435}\u{447}\u{430}\u{43d}\u{441}\u{43a}\u{430}\u{44f}" do
                        %br/
                  %li
                    %h4 Phone
                    %p
                      %strong Отдел технологии и дизайна:
                      %br/
                      +380 673947080
                    %p
                      %strong Дирекция:
                      %br/
                      +380 677008835
              .medium-6.columns.social-links.right
                %ul
                  / legal notice
                  %li.show-for-medium-up
                    %h4 Website
                    %p
                      %a{:href => "http://www.vinner-plus.com"} www.vinner-plus.com
                  %li.show-for-medium-up
                    %h4 Найди нас на
                    / Begin of Social links
                    .socialnet
                      %a{:href => "#"}
                        %i.ion.ion-social-facebook
                      %a{:href => "#"}
                        %i.ion.ion-social-instagram
                      %a{:href => "#"}
                        %i.ion.ion-social-twitter
                      %a{:href => "#"}
                        %i.ion.ion-social-pinterest
                      %a{:href => "#"}
                        %i.ion.ion-social-tumblr
                    / End of Social links
                  %li
                    %p
                      %img.logo{:alt => "Logo", :src => "img/logo_large.png"}/
    / End of page SubSection
    #s-message.slide.fp-slide.fp-table{:style => "width: 50%;"}
      .fp-tableCell.fp-content{:style => "height: 609px;"}
        %section.content
          %header.p-title
            %h3
              Напишите нам!
              %i.ion.ion-email
            %ul.buttons
              %li.show-for-medium-up
                %a{:href => "#con", :title => "Контакты"}
                  %i.ion.ion-android-information
              %li
                %a{:href => "#con/1", :title => "Написать нам"}
                  %i.ion.ion-email
              %li
                %a{:href => "#con/2", :title => "Онлайн ЧАТ"}
                  %i.ion.ion-chatboxes
          /
          /      <li>
          /      <a title="Message" href="#contact/message"><i class="ion ion-email"></i></a>
          /      </li>
          / Begin Of Page SubSction
          .page-block.c-right.v-zoomIn
            .wrapper
              %div
                %form.message.form.send_message_form{:action => "ajaxserver/serverfile.php", :method => "get"}
                  .fields.clearfix
                    .input
                      %label{:for => "mes-name"} Имя
                      %input#mes-name{:name => "name", :placeholder => "Ваше имя", :required => "", :type => "text"}/
                    .buttons
                      %button#submit-message.button.email_b{:name => "submit_message"} Ok
                  .fields.clearfix
                    .input
                      %label{:for => "mes-email"} Email
                      %input#mes-email{:name => "email", :placeholder => "Ваш Email", :required => "", :type => "email"}/
                  .fields.clearfix.no-border
                    %label{:for => "mes-text"} Сообщение
                    %textarea#mes-text{:name => "message", :placeholder => "Ваше сообщение напишите здесь ...", :required => ""}
                    %div
                      %p.message-ok.invisible Ваше сообщение отправлено, СПАСИБО!.
    / End Of Page SubSction
    #s-chat.slide.fp-slide.fp-table{:style => "width: 50%;"}
      .fp-tableCell.fp-content{:style => "height: 609px;"}
        %section.content
          %header.p-title
            %h3
              Он-лайн ЧАТ
              %i.ion.ion-chatboxes
            %ul.buttons
              %li.show-for-medium-up
                %a{:href => "#con", :title => "Контакты"}
                  %i.ion.ion-android-information
              %li
                %a{:href => "#con/1", :title => "Написать нам"}
                  %i.ion.ion-email
              %li
                %a{:href => "#con/2", :title => "Онлайн ЧАТ"}
                  %i.ion.ion-chatboxes

  .fp-controlArrow.fp-prev
  .fp-controlArrow.fp-next

app/views/application/_facebook.html.haml
%iframe{src: 'https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fsorochkaoptcom&tabs=timeline&width=340&height=500&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=true&appId=469203883283146',
            width: '340', height: '500', style: 'border:none;overflow:hidden', scrolling: 'no', frameborder: '0',
            allowTransparency: 'true', class: 'fb-page'}

app/views/application/_feedback.html.haml
#s-register.section.page-register.page.page-cent.fp-section.fp-table{"data-anchor" => "reg", :style => "height: 609px;"}
  .fp-tableCell.fp-content{:style => "height: 609px;"}
    %section.content
      %header.p-title
        %h3
          Подписка
          %i.ion.ion-compose
      %div
        %form#mail-subscription.form.magic.send_email_form{:action => "ajaxserver/serverfile.php", :method => "get"}
          %p.invite.center Пожалуйста, впишите ваш email чтобы оставаться с нами на связи
          .fields.clearfix
            .input
              %label{:for => "reg-email"} Email
              %input#reg-email.email_f{"data-validation-type" => "email", :name => "email", :placeholder => "ваш@элетронный.адресс", :required => "", :type => "email"}/
            .buttons
              %button#submit-email.button.email_b{:name => "submit_email"} Ok
          %p.email-ok.invisible
            %strong Спасибо вам
            за Вашу подписку. Мы свяжемся с Вами обязательно.
    %footer.p-footer.p-scrolldown
      %a{:href => "#ab"}
        .arrow-d
          .before про
          .after Vinner Plus
          .circle

app/views/application/_footer.html.haml
%footer.page-footer
  .col-sm-3
    %a{href: '/privatpolicy'}
      Privacy Policy
    %a{href: "/sitetopic"}
      = t(:_topic)
  .copyright
    %p
      %span
        %a{:href => "#", :target => "_blank"}
          %i.ion.icon.ion-social-facebook
        %a{:href => "#", :target => "_blank"}
          %i.ion.icon.ion-social-instagram
        %a{:href => "#", :target => "_blank"}
          %i.ion.icon.ion-social-twitter
    %p
      \&copy; #{Time.now.year}
      %span.pink 
        Vinner-Plus
      All Rights Reserved

app/views/application/_lang.html.haml
.lang_panel
  - langA = ['uk', 'ru', 'en', 'be', 'tr', 'pl' ]
  - req = request.fullpath
  - langA.each do |lang|
    - lang == 'uk' && ((flag = 'ua') && (title = "українською"))
    - lang == 'ru' && ((flag = 'ru') && (title = "по-русски"))
    - lang == 'en' && ((flag = 'us') && (title = "for english"))
    - lang == 'tr' && ((flag = 'tr') && (title = "türkçe"))
    - lang == 'pl' && ((flag = 'pl') && (title = "w języku polskim"))
    - lang == 'be' && ((flag = 'by') && (title = "па беларуску"))
    %a{href: "http://#{lang}.mirmarbi.com/#{req}", class: "flag-icon flag-#{lang}", title: "#{title}", alt: "#{title}"}
      %img{src: "/flags/#{flag}.png"}

app/views/application/_leftpanel.html.haml
%nav.quick-link.count-6.nav-left
  %ul#qmenu
    %li.active{"data-menuanchor" => "tut"}
      %a{:href => "#tut"}
        %i.icon.ion.ion-home
      %span.title Главная
    %li{"data-menuanchor" => "cat"}
      %a{:href => "#cat"}
        %i.icon.ion.ion-android-archive
      %span.title Каталог
    %li{"data-menuanchor" => "fback"}
      %a{:href => "#fback"}
        %i.icon.ion.ion-compose
      %span.title Будь на связи
    %li{"data-menuanchor" => "ab"}
      %a{:href => "#ab"}
        %i.icon.ion.ion-android-information
      %span.title Про нас
    %li{"data-menuanchor" => "con"}
      %a{:href => "#con"}
        %i.icon.ion.ion-android-call
      %span.title Контакт
    %li{"data-menuanchor" => "con/1"}
      %a{:href => "#con/1"}
        %i.icon.ion.ion-email
      %span.title Написать нам
    %li{"data-menuanchor" => "con/2"}
      %a{:href => "#con/2"}
        %i.icon.ion.ion-chatboxes
      %span.title Онлайн ЧАТ

app/views/application/_menu.html.haml
.logo
  %a{:href => "#{root_path}"}
    %img{:alt => "Logo Brand", :src => "/img/logo_large.png"}/
.menu.clearfix
  %a{:href => "/#cat"}
    %i{class: [ 'fa', 'fa-book']}
    =t(:_catalog)
  %a{:href => "/#ab"}
    %i{class: [ 'fa', 'fa-info-circle']}
    =t(:_about)
  %a{:href => "/#con"}
    %i{class: [ 'fa', 'fa-pencil-square-o']}
    =t(:_contact_us)
.logo-container
  %img.h-logo{:alt => "Logo", :src => "/img/logo_only.png"}/
%ul{class: ['nav', 'navbar-nav', 'navbar-right']}
  /%li{class: ['direct', 'btn-abs-cart']}
  / %a{href: "#order", class: 'button btn'}
  /  %i{class: [ 'glyphicon', 'glyphicon-shopping-cart']}
  / .inner
  /  %span.item
  /   0 item
  /%br
  /%span.value
  / 0 $
  - if current_user
    %li{class: ['remote-modal']}
      %a{href: '/sign_out', class: 'gradient'}
        %i{class: [ 'fa', 'fa-sign-out']}
        = t('layouts.header.logout')
    - if current_user.is_admin
      %li{class: ['remote-modal', 'btn-nav-adminpanel']}
        %a{href: '/adminpanel', class: 'gradient'}
          %i{class: [ 'fa', 'fa-cogs']}
          Admin panel
    - else
      %li{class: ['direct', 'btn-nav-user', 'remote-modal']}
        = link_to edit_user_password_path(current_user) do
          %i{class: [ 'fa', 'fa-user']}
          =t('account')
  - else
    %li{class: ['remote-modal']}
      = link_to remote_sign_in_path, :remote => true do
        %i{class: [ 'fa', 'fa-sign-in']}
        = t('layouts.header.login')
    %li{class: ['remote-modal']}
      = link_to remote_sign_up_path, :remote => true do
        %i{class: [ 'fa', 'fa-user-plus']}
        = t('registrations.new.sign_up')

app/views/application/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    - type = 'info'
    - msgd = msg.downcase
    - msgd['success'] && type = 'success'
    - ( msgd['error'] || msgd['fail'] || msgd['invalid'] ) && type= 'danger'
    %div{:class => "alert alert-#{type}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/application/_vkontakte.html.haml
#vk_groups
:javascript
  VK.Widgets.Group("vk_groups", {mode: 2, wide: 1, width: "340", height: "600", color3: "#000046"}, 117776763);