config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :galleries

  get 'home' => 'static_pages#home', :as => 'home'
  get 'contacts' => 'static_pages#contacts', :as => 'contacts'
  get 'about' => 'static_pages#about', :as => 'about'
  get 'order' => 'static_pages#order', :as => '_order'
  get 'userslist' => 'static_pages#userslist', :as => 'userslist'
  get 'privatpolicy' => 'static_pages#privatpolicy', :as => 'privatpolicy'
  get 'sitetopic' => 'static_pages#sitetopic', :as => 'sitetopic'
  get 'catalog' => 'static_pages#catalog', :as => 'catalog'
  get 'adminpanel' => 'static_pages#adminpanel', :as => 'adminpanel'
  get "sitemap.xml" => "static_pages#sitemap", format: :xml, as: :sitemap
  get "robots.txt" => "static_pages#robots", format: :text, as: :robots
  get 'facebook' => 'static_pages#facebook', :as => 'facebook'
  get 'vkontakte' => 'static_pages#vkontakte', :as => 'vkontakte'

  devise_for :users, :controllers => { registrations: 'registrations',
                                       omniauth_callbacks: 'omniauth_callbacks', sessions: 'sessions' }
  resources :users

  match 'remote_sign_up', to: 'remote_content#remote_sign_up', via: [:get]
  match 'remote_sign_in', to: 'remote_content#remote_sign_in', via: [:get]

  match '/users/:id/finish_signup' => 'users#finish_signup',
        via: [:get, :patch], as: :finish_signup

  resources :categories do
    member do
      get :session_update
      get :catalog
      post :temp_update
      patch :temp_update
    end
  end

  devise_scope :user do
    get "sign_out", to: "devise/sessions#destroy"
  end

  root 'static_pages#home'

end

app/controllers/remote_content_controller.rb
class RemoteContentController < ApplicationController
end

app/views/remote_content/_remote_sign_in.html.haml
#sign_in_modal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"}
          %i.fa.fa-times-circle
        %h4#SignInModal.modal-title Вход
        %p в Личный Кабинет
      = simple_form_for(resource, :as => resource_name, :url => session_path(resource_name, :format => :js), :remote => true,  :html => {:class => "form-signin"}) do |f|
        .modal-body
          .avatar
            %img{src: '../no-gravatar.jpg'}
          = f.input :email, :autofocus => true, :label => false, :input_html => {:class => 'form-control'}, :placeholder => "Your email..."
          = f.input :password, :label => false, :input_html => {:class => 'form-control'}, :placeholder => "Your password..."
          - if devise_mapping.rememberable?
            = f.label :remember_me, class:'remember-label'
            = f.check_box :remember_me, class: 'remember', value: 'user_remember_me'
          .modal-footer
            .form-actions
              .modal-social-icons
                %a{ href: '/users/auth/facebook', class: "btn btn-default facebook"}
                  %i.fa.fa-facebook.modal-icons
              = f.button :submit, "Войти!", :class => "circle"

app/views/remote_content/_remote_sign_up.html.haml
#sign_up_modal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"}
          %i.fa.fa-times-circle
        %h4#SignInModal.modal-title Ваш Личный Кабинет
        %p добавьте Ваши данные<br> для его создания!
      = simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name, :format => :js), :remote => true,  :html => {:class => "form-signin"}) do |f|
        .modal-body
          .avatar
            %img{src: '../no-gravatar.jpg'}
          = f.input :name, :autofocus => true, :label => false, :input_html => {:class => 'form-control'}, :placeholder => "Your name..."
          = f.input :email, :autofocus => true, :label => false, :input_html => {:class => 'form-control'}, :placeholder => "Your email..."
          = f.input :password, :label => false, :input_html => {:class => 'form-control'}, :placeholder => "New password..."
          = f.input :password_confirmation, :label => false, :input_html => {:class => 'form-control'}, :placeholder => "New password comfirmation..."
        .modal-footer
          .form-actions
            .modal-social-icons
              %a{ href: '/users/auth/facebook', class: "btn btn-default facebook"}
                %i.fa.fa-facebook.modal-icons
            = f.button :submit, "Зарегистрироваться!", :class => "circle"

app/views/remote_content/devise_errors.js.erb
if($('#flash').length > 0) { $('#flash').remove();}
$('.modal-body').prepend("<%= escape_javascript raw(flash_normal) %>");

app/views/remote_content/devise_success_login.js.erb
$('#sign_in_modal .close').click();

if($('#flash').length > 0) { $('#flash').remove(); }
$('body').prepend("<%= escape_javascript raw(flash_normal) %>");

location.reload();

app/views/remote_content/devise_success_sign_up.js.erb
$('#sign_up_modal .close').click();

if($('#flash').length > 0) { $('#flash').remove(); }
$('body').prepend("<%= escape_javascript raw(flash_normal) %>");

location.reload();

app/views/remote_content/remote_sign_in.js.erb
if($('#sign_in_modal').length == 0) {
  $("body").prepend("<%= escape_javascript(render "remote_sign_in", :formats => [:html]) %>");
}

$("#sign_in_modal").removeClass('fade').addClass('show modal-open');
$('body').addClass('show modal-open');
$("#sign_in_modal .close").on('click', function(){
  $("#sign_in_modal").addClass('fade').removeClass('show modal-open');
  $('body').removeClass('show modal-open');
});

//Gravatar
$('#sign_in_modal input.email').change( function() {
  email = $(this).val();
  if(isValidEmailAddress(email)){
    avatar = Gravtastic(email, { size: 300});
    $('.avatar img').attr('src', avatar);
  }
});

app/views/remote_content/remote_sign_up.js.erb
if($('#sign_up_modal').length == 0) {
  $("body").prepend("<%= escape_javascript(render "remote_sign_up", :formats => [:html]) %>");
}

$("#sign_up_modal").removeClass('fade').addClass('show');
$('body').addClass('show modal-open');
$("#sign_up_modal .close").on('click', function(){
  $("#sign_up_modal").addClass('fade').removeClass('show');
  $('body').removeClass('show modal-open');
});
//Gravatar
$('#sign_up_modal input.email').change( function() {
  email = $(this).val();
  if(isValidEmailAddress(email)){
    avatar = Gravtastic(email, { size: 300});
    $('.avatar img').attr('src', avatar);
  }
});